package Contas;

import Trabalho1.ContaEspecial;
import Trabalho1.ContaPoupanca;
import Trabalho1.Contas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klayv
 */
public class JanelaComum extends javax.swing.JFrame {

    Contas obj1;
    ContaPoupanca obj2;
    ContaEspecial obj3;

    public JanelaComum(Contas obj1, ContaPoupanca obj2, ContaEspecial obj3) {

        this.obj1 = obj1;
        this.obj2 = obj2;
        this.obj3 = obj3;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titularcomum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numerocomum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saldocomum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o nome do titular da conta comum:");

        titularcomum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titularcomumActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o número da conta:");

        numerocomum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocomumActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite o saldo inicial:");

        saldocomum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldocomumActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(titularcomum)
                        .addComponent(numerocomum, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(saldocomum)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titularcomum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numerocomum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldocomum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obj1 = new Contas();
        obj1.setNome(titularcomum.getText());
        obj1.setNumero(Integer.parseInt(numerocomum.getText()));
        obj1.setSaldo(Double.parseDouble(saldocomum.getText()));
        new JanelaPoupanca(obj1, obj2, obj3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void titularcomumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titularcomumActionPerformed
    }//GEN-LAST:event_titularcomumActionPerformed

    private void numerocomumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocomumActionPerformed
    }//GEN-LAST:event_numerocomumActionPerformed

    private void saldocomumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldocomumActionPerformed
    }//GEN-LAST:event_saldocomumActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numerocomum;
    private javax.swing.JTextField saldocomum;
    private javax.swing.JTextField titularcomum;
    // End of variables declaration//GEN-END:variables
}
