package Contas;

import Trabalho1.ContaEspecial;
import Trabalho1.ContaPoupanca;
import Trabalho1.Contas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klayv
 */
public class JanelaEspecial extends javax.swing.JFrame {

    /**
     * Creates new form ContaComum
     */
    Contas obj1;
    ContaPoupanca obj2;
    ContaEspecial obj3;

    public JanelaEspecial(Contas obj1, ContaPoupanca obj2, ContaEspecial obj3) {
        initComponents();
        this.obj1 = obj1;
        this.obj2 = obj2;
        this.obj3 = obj3;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titularespecial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numeroespecial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saldoespecial = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        limiteespecial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        multaespecial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o nome do titular da conta especial:");

        titularespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titularespecialActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite o número da conta:");

        numeroespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroespecialActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite o saldo inicial:");

        saldoespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoespecialActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Digite o limite:");

        limiteespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiteespecialActionPerformed(evt);
            }
        });

        jLabel5.setText("Digite a multa para conta:");

        multaespecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multaespecialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titularespecial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroespecial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(saldoespecial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limiteespecial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multaespecial, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titularespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldoespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limiteespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multaespecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        obj3 = new ContaEspecial();
        obj3.setNome(titularespecial.getText());
        obj3.setNumero(Integer.parseInt(numeroespecial.getText()));
        obj3.setSaldo(Double.parseDouble(saldoespecial.getText()));
        obj3.limite = Integer.parseInt(limiteespecial.getText());
        obj3.multa = Double.parseDouble(multaespecial.getText());
        new Operacoes(obj1, obj2, obj3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numeroespecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroespecialActionPerformed
    }//GEN-LAST:event_numeroespecialActionPerformed

    private void titularespecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titularespecialActionPerformed
    }//GEN-LAST:event_titularespecialActionPerformed

    private void saldoespecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoespecialActionPerformed
    }//GEN-LAST:event_saldoespecialActionPerformed

    private void limiteespecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limiteespecialActionPerformed
    }//GEN-LAST:event_limiteespecialActionPerformed

    private void multaespecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multaespecialActionPerformed
    }//GEN-LAST:event_multaespecialActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField limiteespecial;
    private javax.swing.JTextField multaespecial;
    private javax.swing.JTextField numeroespecial;
    private javax.swing.JTextField saldoespecial;
    private javax.swing.JTextField titularespecial;
    // End of variables declaration//GEN-END:variables
}
