package Contas;

import Operacoes.JanelaDeposito;
import Operacoes.JanelaReajustar;
import Operacoes.JanelaSaque;
import Operacoes.JanelaTransferencia;
import Trabalho1.ContaEspecial;
import Trabalho1.ContaPoupanca;
import Trabalho1.Contas;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klayv
 */
public class Operacoes extends javax.swing.JFrame {

    /**
     * Creates new form Operacoes
     */
    Contas obj1;
    ContaPoupanca obj2;
    ContaEspecial obj3;

    public Operacoes(Contas obj1, ContaPoupanca obj2, ContaEspecial obj3) {
        initComponents();
        this.obj1 = obj1;
        this.obj2 = obj2;
        this.obj3 = obj3;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saque = new javax.swing.JButton();
        Deposito = new javax.swing.JButton();
        Transferencia = new javax.swing.JButton();
        Reajustar = new javax.swing.JButton();
        VerSaldos = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Saque.setText("Saque");
        Saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaqueActionPerformed(evt);
            }
        });

        Deposito.setText("Depósito");
        Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositoActionPerformed(evt);
            }
        });

        Transferencia.setText("Transferência");
        Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferenciaActionPerformed(evt);
            }
        });

        Reajustar.setText("Reajustar");
        Reajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReajustarActionPerformed(evt);
            }
        });

        VerSaldos.setText("Ver Saldos");
        VerSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerSaldosActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione a opção desejada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Reajustar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(VerSaldos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Transferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Saque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(Deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deposito, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Saque))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Transferencia)
                    .addComponent(Reajustar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerSaldos)
                    .addComponent(Sair))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaqueActionPerformed
        new JanelaSaque(obj1, obj2, obj3).setVisible(true);
        Operacoes.this.dispose();
    }//GEN-LAST:event_SaqueActionPerformed

    private void DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositoActionPerformed
        new JanelaDeposito(obj1, obj2, obj3).setVisible(true);
        Operacoes.this.dispose();
    }//GEN-LAST:event_DepositoActionPerformed

    private void VerSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerSaldosActionPerformed

        JOptionPane.showMessageDialog(null,
                "Conta Comum: " + obj1.getNome()
                + "\nNúmero: " + obj1.getNumero()
                + "\nSaldo: " + obj1.getSaldo()
                + "\n\nConta Poupança: " + obj2.getNome()
                + "\nNúmero: " + obj2.getNumero()
                + "\nSaldo: " + obj2.getSaldo()
                + "\n\nConta Especial: " + obj3.getNome()
                + "\nNúmero: " + obj3.getNumero()
                + "\nSaldo: " + obj3.getSaldo() );
                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_VerSaldosActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        Operacoes.this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void ReajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReajustarActionPerformed
        new JanelaReajustar(obj1, obj2, obj3).setVisible(true);
        Operacoes.this.dispose();

    }//GEN-LAST:event_ReajustarActionPerformed

    private void TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferenciaActionPerformed
        new JanelaTransferencia(obj1, obj2, obj3).setVisible(true);
        Operacoes.this.dispose();
    }//GEN-LAST:event_TransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deposito;
    private javax.swing.JButton Reajustar;
    private javax.swing.JButton Sair;
    private javax.swing.JButton Saque;
    private javax.swing.JButton Transferencia;
    private javax.swing.JButton VerSaldos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
