package Operacoes;

import Contas.Operacoes;
import Trabalho1.ContaEspecial;
import Trabalho1.ContaPoupanca;
import Trabalho1.Contas;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klayv
 */
public class JanelaSaque extends javax.swing.JFrame {

    /**
     * Creates new form janelasaque
     */
    Contas obj1;
    ContaPoupanca obj2;
    ContaEspecial obj3;

    public JanelaSaque(Contas obj1, ContaPoupanca obj2, ContaEspecial obj3) {
        initComponents();
        this.obj1 = obj1;
        this.obj2 = obj2;
        this.obj3 = obj3;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numsaque = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valorsaque = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Digite o número da conta:");

        numsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsaqueActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor para saque:");

        valorsaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorsaqueActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(numsaque, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(valorsaque)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numsaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorsaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int numSaque = Integer.parseInt(numsaque.getText());
        double valorSaque = Double.parseDouble(valorsaque.getText());

        if(valorSaque<0){
            JOptionPane.showMessageDialog(null, "Valor de saque inválido!");
            new Operacoes(obj1, obj2, obj3).setVisible(true);
            this.dispose();
        }
        else if (numSaque == obj1.getNumero()) {
            int yn = JOptionPane.showConfirmDialog(null, obj1.getNome() + " ,deseja confirmar o saque?", "", JOptionPane.YES_NO_OPTION);

            if (yn == JOptionPane.YES_OPTION) {

                if (valorSaque <= obj1.getSaldo()) {

                    obj1.sacar(valorSaque);
                    JOptionPane.showMessageDialog(null, "Saque efetuado com sucesso!");

                } else {
                    JOptionPane.showMessageDialog(null, "Valor a sacar maior que o saldo da conta.");
                }

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (yn == JOptionPane.NO_OPTION) {

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
            }

        } else if (numSaque == obj2.getNumero()) {

            int yn = JOptionPane.showConfirmDialog(null, obj2.getNome() + " ,deseja confirmar o saque?", "", JOptionPane.YES_NO_OPTION);

            if (yn == JOptionPane.YES_OPTION) {

                if (valorSaque <= obj2.getSaldo()) {
                    obj2.sacar(valorSaque);
                    JOptionPane.showMessageDialog(null, "Saque efetuado com sucesso!");

                } else {
                    JOptionPane.showMessageDialog(null, "Valor a sacar maior que o saldo da conta.");
                }

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (yn == JOptionPane.NO_OPTION) {

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
            }

        } else if (numSaque == obj3.getNumero()) {

            int yn = JOptionPane.showConfirmDialog(null, obj3.getNome() + " ,deseja confirmar o saque?", "", JOptionPane.YES_NO_OPTION);

            if (yn == JOptionPane.YES_OPTION) {

                if (valorSaque <= obj3.getSaldo()) {
                    obj3.sacar(valorSaque);
                    JOptionPane.showMessageDialog(null, "Saque efetuado com sucesso!");

                } else if (valorSaque > obj3.getSaldo() && valorSaque <= obj3.getSaldo() + obj3.limite) {

                    obj3.saqueEspecial(valorSaque);
                    JOptionPane.showMessageDialog(null, "Saque efetuado usando cheque especial!");

                } else {
                    JOptionPane.showMessageDialog(null, "Valor a sacar maior que o saldo da conta.");
                }

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (yn == JOptionPane.NO_OPTION) {

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsaqueActionPerformed

    }//GEN-LAST:event_numsaqueActionPerformed

    private void valorsaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorsaqueActionPerformed

    }//GEN-LAST:event_valorsaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numsaque;
    private javax.swing.JTextField valorsaque;
    // End of variables declaration//GEN-END:variables
}
