package Operacoes;

import Contas.Operacoes;
import Trabalho1.ContaEspecial;
import Trabalho1.ContaPoupanca;
import Trabalho1.Contas;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author klayv
 */
public class JanelaDeposito extends javax.swing.JFrame {

    /**
     * Creates new form janelasaque
     */
    Contas obj1;
    ContaPoupanca obj2;
    ContaEspecial obj3;

    public JanelaDeposito(Contas obj1, ContaPoupanca obj2, ContaEspecial obj3) {
        initComponents();
        this.obj1 = obj1;
        this.obj2 = obj2;
        this.obj3 = obj3;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numdep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        valordep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Digite o número da conta:");

        numdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdepActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor para depósito:");

        valordep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valordepActionPerformed(evt);
            }
        });

        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(numdep, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addComponent(valordep)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valordep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numdepActionPerformed

    private void valordepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valordepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valordepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int numDep = Integer.parseInt(numdep.getText());
        double valorDep = Double.parseDouble(valordep.getText());
        
        if(valorDep<0){
            JOptionPane.showMessageDialog(null, "Valor de depósito inválido!");
            new Operacoes(obj1, obj2, obj3).setVisible(true);
            this.dispose();
        }
        else if (numDep == obj1.getNumero()) {

            int yn = JOptionPane.showConfirmDialog(null, obj1.getNome() + " ,deseja confirmar o depósito?", "", JOptionPane.YES_NO_OPTION);

            if (yn == JOptionPane.YES_OPTION) {

                obj1.depositar(valorDep);
                JOptionPane.showMessageDialog(null, "Depósito realizado com sucesso!");

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (yn == JOptionPane.NO_OPTION) {

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
            }

        } else if (numDep == obj2.getNumero()) {

            int yn = JOptionPane.showConfirmDialog(null, obj2.getNome() + " ,deseja confirmar o depósito?", "", JOptionPane.YES_NO_OPTION);

            if (yn == JOptionPane.YES_OPTION) {

                obj2.depositar(valorDep);
                JOptionPane.showMessageDialog(null, "Depósito realizado com sucesso!");

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (yn == JOptionPane.NO_OPTION) {

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();
            }

        } else if (numDep == obj3.getNumero()) {

            int op = JOptionPane.showConfirmDialog(null, obj3.getNome() + " ,deseja confirmar o depósito?", "", JOptionPane.YES_NO_OPTION);

            if (op == JOptionPane.YES_OPTION) {

                obj3.depositar(valorDep);
                JOptionPane.showMessageDialog(null, "Depósito realizado com sucesso!");

                new Operacoes(obj1, obj2, obj3).setVisible(true);
                this.dispose();

            } else if (op == JOptionPane.NO_OPTION) {
                new Operacoes(obj1, obj2, obj3).setVisible(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numdep;
    private javax.swing.JTextField valordep;
    // End of variables declaration//GEN-END:variables
}
